# ----------------------------
# Makefile Options
# ----------------------------

NAME = BTF
DESCRIPTION = "Converts a hexstring from IEEE-754 Floating Point representation to decimal representation"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
